theme: jekyll-theme-slate
include:
    - AlchimistischeGebraeue.md
    - ArkaneMagie&Lektionen.md
    - Artefakte&MagischeGegenstaende.md
    - Fertigkeiten.md
    - Foki&Zauberhelfer.md
    - Geschenke&DornenDerNatur.md
    - GildenBuendeUndOrden.md
    - GoettlicheMagie.md
    - HandwerksHandbuch.md
    - Kampfschulen-Mini.md
    - Kampfschulen.md
    - Kreaturen.md
    - Lektionen&Berufswege.md
    - Rassen.md
    - ReadMe.md
    - Regionen.md
    - Schwarzmarkt.md
    - Vorzuege&Schwaechen.md